setup maven project and actions
teragrep/hbs_03 pull request #1
Opened 2024-12-17 13:27 UTC by elliVM

adds maven project and plugins, license header, eclipse java format settings and github actions ci and upload release.

- maven plugins
- Junit 5
- slf4j and logback
- equalsverifier 
- apache rat
- checkstyle
- spotless
- enforces
- jacoco
- surefire

2024-12-18 08:46 UTC, kortemik commented
@StrongestNumber9 please peer review first

2024-12-18 14:05 UTC, StrongestNumber9 requested changes

2024-12-18 14:05 UTC, StrongestNumber9 commented on pom.xml
> +                <banDynamicVersions></banDynamicVersions>
Misses com.teragrep snapshot ignore clause https://github.com/teragrep/mvn_01/tree/main/enforcer

2024-12-18 14:05 UTC, StrongestNumber9 commented on pom.xml
> +        <version>2.30.0</version>
Use version 2.43.0 since project is java11+ as mentioned in https://github.com/teragrep/mvn_01/tree/main/formatter

2024-12-18 14:05 UTC, StrongestNumber9 commented on pom.xml
> +            <exclude>license-header</exclude>
Should not require license-header to be excluded since it should include the wanted license

2024-12-18 14:05 UTC, StrongestNumber9 commented on pom.xml
> +        <version>3.0.0-M5</version>
Seems outdated

2024-12-18 14:05 UTC, StrongestNumber9 commented on pom.xml
> +    <profile>
Maven central has different workflow now: https://github.com/teragrep/mvn_01/blob/main/workflows/pom.xml#L118

2025-01-02 06:41 UTC, elliVM commented on .github/workflows/ci.yaml
> +name: CI
Updated to include CI and Coverity workflows

2025-01-02 06:41 UTC, elliVM commented on license-header
> + * Teragrep Configuration Library for Java (cnf_01)
Fixed

2025-01-02 06:42 UTC, elliVM commented on pom.xml
> +              <rules>
Added banned dependencies

2025-01-02 06:42 UTC, elliVM commented on pom.xml
> +                <banDynamicVersions></banDynamicVersions>
Added ignore snapshot clause

2025-01-02 06:43 UTC, elliVM commented on pom.xml
> +        <version>2.30.0</version>
changes spotless version to 2.43.0

2025-01-02 06:43 UTC, elliVM commented on pom.xml
> +            <exclude>license-header</exclude>
removed exclude clause for license-header

2025-01-02 06:44 UTC, elliVM commented on pom.xml
> +        <version>3.0.0-M5</version>
updated to version 3.3.1

2025-01-02 06:44 UTC, elliVM commented on pom.xml
> +    <profile>
updated to new workflow

2025-01-02 06:56 UTC, elliVM commented
Should be all fixed now including new workflows CI and Coverity. could you take a look @StrongestNumber9 ?

2025-01-02 07:49 UTC, StrongestNumber9 requested changes
Looks better, some java versions needs to be updated

2025-01-02 07:49 UTC, StrongestNumber9 commented on .github/workflows/ci.yaml
> +          java-version: 8.0.292+10
Should be java 11

2025-01-02 07:49 UTC, StrongestNumber9 commented on .github/workflows/coverity.yaml
> +          java-version: 8.0.292+10
Should be java 11

2025-01-02 08:10 UTC, elliVM commented on .github/workflows/coverity.yaml
> +          java-version: 8.0.292+10
updated to Java 11

2025-01-02 08:28 UTC, StrongestNumber9 reviewed
Looks good to me aside some version related questions, good for @kortemik to review as well

2025-01-02 08:28 UTC, StrongestNumber9 commented on pom.xml
> +      <version>3.0.0-alpha-4</version>
We are using hbase 2.6.0, will this 3.0.0 be a problem?

2025-01-02 08:28 UTC, StrongestNumber9 commented on pom.xml
> +      <version>3.16.1</version>
Version `3.17.1` is used in https://github.com/teragrep/mvn_01/tree/main/equalsverifier

2025-01-02 09:46 UTC, kortemik reviewed
otherwise good, check @StrongestNumber9 comments about versions

2025-01-02 10:09 UTC, kortemik commented on pom.xml
> +      <version>3.0.0-alpha-4</version>
2.6.1 is latest stable, please use it

2025-01-02 10:09 UTC, kortemik commented on pom.xml
> +      <version>3.16.1</version>
please update to 3.17.1

2025-01-02 10:21 UTC, kortemik approved these changes

2025-01-02 10:22 UTC, StrongestNumber9 approved these changes
lgtm

2025-01-02 10:30 UTC, merged